# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar/')),
                ('bio', models.TextField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='screenshot/')),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(upload_to='screenshot/')),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
