# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190315_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='the_user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='the_user',
            new_name='username',
        ),
    ]
